server:
  port: 7777
spring:
  application.name: Core-Service
  datasource:
    postgresql:
      jdbc-url: jdbc:postgresql://localhost:5432/mydb
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
  # MongoDB Configuration
#  data:
#    mongodb:
##      uri: mongodb://admin:password@localhost:27017/configdb?authSource=admin
#      host: localhost
#      port: 27017
#      database: configdb
#      username: admin
#      password: password
#      authentication-database: configdb



#    database: configdb
#    authentication-database: admin
springdoc:
  openapi:
    api-docs:
      path: /api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

application:
  security:
    jwt:  # this should e store in more secure way in production like AWS keystore
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000


logging:
  level:
    org:
      springframework:
        security=DEBUG:


# add logging later on