server:
  port: 7777
spring:
  application.name: Core-Service
  datasource:
    postgresql:
      jdbc-url: jdbc:postgresql://localhost:5432/mydb
      username: ${ENV_POSTGRES_USER:user}
      password: ${ENV_POSTGRES_PASSWORD:password}
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

springdoc:
  openapi:
    api-docs:
      path: /api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

application:
  security:
    jwt:  # this should e store in more secure way in production like AWS keystore or env
      secret-key: ${ENV_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${ENV_TOKEN_EXPIRATION:86400000}
      refresh-token:
        expiration: ${ENV_TOKEN_REFRESH:604800000}


#logging:
#  level:
#    org:
#      springframework:
#        security=DEBUG:


# add logging later on